/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.upgrade;

import dev.upgrade.acl.ExternalSystemAcl;
import dev.upgrade.acl.Gearbox;
import dev.upgrade.acl.GearboxAcl;
import dev.upgrade.gearbox.GearboxDriver;

public class App {

    public static void main(String[] args) {
        var gearbox = new Gearbox();
        gearbox.setGearBoxCurrentParams(new Integer[] {1, 1});
        gearbox.setMaxDrive(6);

        var driver = new GearboxDriver(new ExternalSystemAcl(), new GearboxAcl(gearbox));
        driver.increaseGear();
    }
}
